### ISSUE TITLE
UnicodeDecodeError while running vpip install -g poetry

### ISSUE THREAD

**Issue by andoresuperesu** [eight04/vpip#23]
Got the Following error while attempting an install of poetry on python 3.7.5 using `vpip install -g poetry`. Same install doesnt fail using pip. Thanks for the amazing library, I can give more details if necessary. I'm quite rusty in python and have to spend a little longer to find the guilty code.

Please see the full output bellow:
```
C:\Users\aperez>vpip install -g poetry
building venv at C:\Users\aperez\.vpip\pkg_venvs\poetry
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1
Collecting poetry
  Using cached https://files.pythonhosted.org/packages/c9/76/214acc400055aa0045ed21ce25378225b1887c5c091f99476955bf9f6984/poetry-0.12.17-py2.py3-none-any.whl
Collecting tomlkit<0.6.0,>=0.5.1
  Using cached https://files.pythonhosted.org/packages/3e/30/7c2693fc50bd466285ec22bf02ee344be1bde3e2e8267e302fdc82d11f2d/tomlkit-0.5.8-py2.py3-none-any.whl
Collecting jsonschema<4.0,>=3.0a3
  Using cached https://files.pythonhosted.org/packages/ce/6c/888d7c3c1fce3974c88a01a6bc553528c99d3586e098eee23e8383dd11c3/jsonschema-3.1.1-py2.py3-none-any.whl
Collecting pyparsing<3.0,>=2.2
  Using cached https://files.pythonhosted.org/packages/a3/c4/7828cf9e71ce8fbd43c1e502f3fdd0498f069fcf9d1c268205ce278ae201/pyparsing-2.4.4-py2.py3-none-any.whl
Collecting cachecontrol[filecache]<0.13.0,>=0.12.4
  Using cached https://files.pythonhosted.org/packages/5e/f0/2c193ed1f17c97ae539da7e1c2d48b80d8cccb1917163b26a91ca4355aa6/CacheControl-0.12.5.tar.gz
Collecting shellingham<2.0,>=1.1
  Using cached https://files.pythonhosted.org/packages/2d/ac/e8a34d4b3d24bf554f40651b2aac549a3fc7223725bf10fbdfe2083b6372/shellingham-1.3.1-py2.py3-none-any.whl
Collecting requests-toolbelt<0.9.0,>=0.8.0
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting html5lib<2.0,>=1.0
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting cachy<0.3,>=0.2
  Using cached https://files.pythonhosted.org/packages/26/37/8ce3e7b330078b6797a34e79a80a8ad6935e404a3b903765417182c9ce19/cachy-0.2.0-py2.py3-none-any.whl
Collecting cleo<0.7.0,>=0.6.7
  Using cached https://files.pythonhosted.org/packages/a7/b9/270301a3a87587f09bc3985973f2e362ffa45fa5fcd5128501516b2f5e31/cleo-0.6.8-py2.py3-none-any.whl
Collecting pyrsistent<0.15.0,>=0.14.2
  Using cached https://files.pythonhosted.org/packages/8c/46/4e93ab8a379d7efe93f20a0fb8a27bdfe88942cc954ab0210c3164e783e0/pyrsistent-0.14.11.tar.gz
Collecting requests<3.0,>=2.18
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting pkginfo<2.0,>=1.4
  Using cached https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\aperez\.vpip\pkg_venvs\poetry\lib\site-packages (from jsonschema<4.0,>=3.0a3->poetry) (41.2.0)
Collecting attrs>=17.4.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting importlib-metadata
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting six>=1.11.0
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting msgpack
  Downloading https://files.pythonhosted.org/packages/41/0a/49b522c5b23006d60669ec8dc97558e91880673e170108e0e9e21fc452e3/msgpack-0.6.2-cp37-cp37m-win_amd64.whl (68kB)
     |████████████████████████████████| 71kB 353kB/s
Collecting lockfile>=0.9
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting webencodings
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting pastel<0.2.0,>=0.1.0
  Using cached https://files.pythonhosted.org/packages/09/b9/ca6434777928cc4e25cd17a8d2a913f3c2877ce54c5a7b7c18bf646ff257/pastel-0.1.1-py2.py3-none-any.whl
Collecting pylev<2.0,>=1.3
  Using cached https://files.pythonhosted.org/packages/40/1c/7dff1d242bf1e19f9c6202f0ba4e6fd18cc7ecb8bc85b17b2d16c806e228/pylev-1.3.0-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting zipp>=0.5
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting more-itertools
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Installing collected packages: tomlkit, six, pyrsistent, attrs, more-itertools, zipp, importlib-metadata, jsonschema, pyparsing, urllib3, idna, chardet, certifi, requests, msgpack, lockfile, cachecontrol, shellingham, requests-toolbelt, webencodings, html5lib, cachy, pastel, pylev, cleo, pkginfo, poetry
    Running setup.py install for pyrsistent ... done
    Running setup.py install for cachecontrol ... done
Successfully installed attrs-19.3.0 cachecontrol-0.12.5 cachy-0.2.0 certifi-2019.9.11 chardet-3.0.4 cleo-0.6.8 html5lib-1.0.1 idna-2.8 importlib-metadata-0.23 jsonschema-3.1.1 lockfile-0.12.2 more-itertools-7.2.0 msgpack-0.6.2 pastel-0.1.1 pkginfo-1.5.0.1 poetry-0.12.17 pylev-1.3.0 pyparsing-2.4.4 pyrsistent-0.14.11 requests-2.22.0 requests-toolbelt-0.8.0 shellingham-1.3.1 six-1.13.0 tomlkit-0.5.8 urllib3-1.25.6 webencodings-0.5.1 zipp-0.6.0
Traceback (most recent call last):
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\aperez\AppData\Local\Programs\Python\Python37\Scripts\vpip.exe\__main__.py", line 9, in <module>
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\site-packages\vpip\cli.py", line 57, in cli
    module.run(ns)
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\site-packages\vpip\commands\install.py", line 33, in run
    install_global(ns.PACKAGE)
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\site-packages\vpip\commands\install.py", line 58, in install_global
    pip_api.install(pkg, upgrade=upgrade, latest=latest)
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\site-packages\vpip\pip_api.py", line 40, in install
    return show([require.name])[0]
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\site-packages\vpip\pip_api.py", line 76, in show
    for line in execute_pip("{} {}".format(cmd, " ".join(packages)), True):
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\site-packages\vpip\execute.py", line 24, in do_execute
    for line in process.stdout:
  File "c:\users\aperez\appdata\local\programs\python\python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 130: invalid continuation byte
```

**Comment by eight04** [comment]
I guess we have to use `-X utf8` option when we want to capture the output of the subprocess:
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8
