### ISSUE TITLE
Lowercase envvar path

### ISSUE THREAD

**Issue by jayvdb** [eight04/vpip#5]
The code uses lowercase envvar name `path` instead of `PATH`.

This results in
```py
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/vpip/__main__.py", line 2, in <module>
    cli()
  File "/usr/lib/python3.7/site-packages/vpip/cli.py", line 57, in cli
    module.run(ns)
  File "/usr/lib/python3.7/site-packages/vpip/commands/list.py", line 20, in run
    print_local_packages(check_outdated=ns.outdated)
  File "/usr/lib/python3.7/site-packages/vpip/commands/list.py", line 42, in print_local_packages
    vv = venv.get_current_venv()
  File "/usr/lib/python3.7/site-packages/vpip/venv.py", line 50, in get_current_venv
    return Venv(".venv")
  File "/usr/lib/python3.7/site-packages/vpip/venv.py", line 98, in __init__
    get_path_without_venv(os.environ["path"], self.old_env_dir)
  File "/usr/lib64/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'path'
```

patch coming

**Comment by eight04** [comment]
Good catch. I didn't know that `os.environ` behaves differently on different OS.
https://stackoverflow.com/questions/7797269/python-environment-case-senstivity-os-environ
