### ISSUE TITLE
pylint vs six breaking CI

### ISSUE THREAD

**Issue by jayvdb** [eight04/vpip#6]
build of current master https://travis-ci.org/jayvdb/vpip/builds/601646066

pip install emits and ignores error
```
astroid 2.3.2 has requirement six==1.12, but you'll have six 1.11.0 which is incompatible.
```

and then

```
$ python cute.py test
> Task: test
> Cmd: pylint vpip cute.py test.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/lint.py", line 1608, in __init__
    linter.check(args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/lint.py", line 938, in check
    self._do_check(files_or_modules)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/lint.py", line 1071, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/lint.py", line 1154, in check_astroid_module
    walker.walk(ast_node)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/utils.py", line 1266, in walk
    cb(astroid)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pylint/checkers/variables.py", line 1582, in visit_import
    module = next(node.infer_name_module(parts[0]))
AttributeError: 'Import' object has no attribute 'infer_name_module'
Command 'pylint vpip cute.py test.py' returned non-zero exit status 1.
```

**Comment by jayvdb** [comment]
The `==` pins in `requirements.txt` are the cause of this problem.

**Comment by eight04** [comment]
We have to pin sub-dependencies. Related: #3
