### ISSUE TITLE
ContextualVersionConflict error when building rpm

### ISSUE THREAD

**Issue by jayvdb** [eight04/vpip#9]
vpip fails due to needing an old setuptools

```py
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 41.0.1 (/home/python3.7/lib/python3.7/site-packages), Requirement.parse('setuptools~=40.7'), {'vpip'})
```

I guess `setuptools>=40.7` would solve that, but the other pins also need to be re-checked.

**Comment by eight04** [comment]
How did you get this error?

**Comment by jayvdb** [comment]
;-)

by building my own rpm
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-vpip

**Comment by eight04** [comment]
I don't have a Linux machine and I don't know how the rpm is built. `sdist` and `bdist_wheel` completes successfully while setuptools@41.4.0 is installed.

I'm not sure why it generates this error while building. Dependencies should only be processed by the library user instead of the author.

**Comment by jayvdb** [comment]
This is a sdist+unix problem.  setuptools creates a bin wrapper which uses `pkg_resources` , and pkg_resources checks all the pins of the package it is about to invoke. So when the package says `setuptools~=40.7`, `pkg_resources` will refuse to run the bin wrapper when setuptools 41 is installed.

**Comment by jayvdb** [comment]
I'll recheck this tmr.

**Comment by jayvdb** [comment]
Changing this to `setuptools~=41.4` caused me the opposite problem -- I had v41.0.1 installed, which isnt compatible with `setuptools~=41.4`.

I updated my setuptools and all was good again.

Does one of these fail with lower setuptools versions?

```console
vpip/commands/__init__.py:from pkg_resources import resource_listdir
vpip/dependency.py:from pkg_resources import parse_requirements
vpip/pip_api.py:from pkg_resources import Requirement
```

I suggest using tox or https://github.com/theacodes/nox , with `setuptools` as a factor in the matrix, so the test suite runs against a few versions of setuptools to ensure the lowest setuptools version is known and supported (or bumped when required), and the latest setuptools is also tested to ensure ongoing compatibility.

**Comment by eight04** [comment]
> Does one of these fail with lower setuptools versions?
> 
> ```
> vpip/commands/__init__.py:from pkg_resources import resource_listdir
> vpip/dependency.py:from pkg_resources import parse_requirements
> vpip/pip_api.py:from pkg_resources import Requirement
> ```

I think they work fine from 40.5: https://github.com/eight04/vpip/blame/b2e64bd98acf85d512694814ced6efab628500f9/setup.cfg#L29

> I suggest using tox or https://github.com/theacodes/nox , with `setuptools` as a factor in the matrix, so the test suite runs against a few versions of setuptools to ensure the lowest setuptools version is known and supported (or bumped when required), and the latest setuptools is also tested to ensure ongoing compatibility.

`setuptools` is a dependency. If we want to test the compatibility with dependencies, we should test all of them. But it doesn't worth it IMHO.

---

This is a build issue. We should fix the build process. It could be a bug in setup.py or the build script. But we shouldn't modify the production code.

**Comment by jayvdb** [comment]
https://github.com/ninjaaron/fast-entry_points is another solution specifically for the setuptools created entry point script.  It removes that use of `pkg_resources`, so the bin wrapper is like the one created for wheels.

**Comment by eight04** [comment]
Now we don't depend on setuptools. Would you like to try it again?
